### ISSUE TITLE
El delimitador causa problemas al momento cambiarlo

### ISSUE THREAD

**Issue by WindB3NJA** [WindB3NJA/Solemne-3--Data-Analisis-#2]
al cambiar de ; a , el dataframe que lo muestra muere asi qu eso se debe cambiar 
![image](https://github.com/user-attachments/assets/5e4a1f4f-6c3f-453b-a0d5-986277caff0b)

**Comment by Simon-Aspee** [comment]
Es necesario que el usuario ingrese un limitador? por que ya lo arregle internamente (Linea 14)

**Comment by WindB3NJA** [comment]
Dpende necesariamente de si es csv

**Comment by WindB3NJA** [comment]
Se elimino el cambio por la barra lateral para el cambio de data frame
